# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clockiebox - code noob
email: petruaugustindesign@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bacon pancakes im making bacon pancakes
baseurl: "" # the subpath of your site, e.g. /blog
url: "clockiebox.github.io" # the base hostname & protocol for your site
github_username:  clockiebox

# Build settings
markdown: kramdown
